### ISSUE TITLE
Version 1.1 not available using Pods

### ISSUE THREAD

**Issue by TomKremer** [mdznr/What-s-New#19]
Hi,

Version 1.1 is not available using CocoaPods

Best

**Comment by codigodelsur** [comment]
![](http://i.imgur.com/GI46QEz.png)

**Comment by mdznr** [comment]
Haha, nice graphic! I'm vaguely familiar with cocoa pods, so I'm not sure what is required to do this. Feel free to create a pull request! Thanks!

**Comment by RyanBertrand** [comment]
I think it is updating the cocoapods trunk.  Your repo podspec seems correct.

http://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Comment by hashier** [comment]
Would like to see 1.1 as well on cocoa pods

**Comment by mdznr** [comment]
Feel free to submit a pull request as I don't understand how cocoa pods really works.

**Comment by eytanbiala** [comment]
Only the owner or authorized contributes can push a new version. You can need to follow [this guide](https://guides.cocoapods.org/making/making-a-cocoapod.html#release) to push a new version, or you can [add someone as a contributor](https://guides.cocoapods.org/making/getting-setup-with-trunk.html#adding-other-people-as-contributors). I'd be happy to do it.

If you are already authorized, you should be able to run `pod trunk push MTZWhatsNew.podspec` in your terminal to push the latest version to CocoaPods.

**Comment by hashier** [comment]
Since you are the maintainer of this project it would be you who can claim the pod spec on cocoa pods, of course someone from here could do the same but I guess it would be best if you just follow the tutorial to be the "owner" of this pod and then add someone from here to be a contributor so someone else could fix everything but you would still be the owner of the spec and not someone else.

There is no pull request we can provide here

**Comment by mdznr** [comment]
Thanks for the help!

https://github.com/CocoaPods/Specs/commit/53c8d6915d8801cb290e08ac2ac5a6a2c252ff0b
